import pandas as pd

data = pd.DataFrame({
    'education_class': ['PhD'],
    'age_class': [1],
    'exp_overall_class': [3.0],
    'exp_field_class': [1],
    'education_class': [False],
    'age_class': [False],
    'exp_overall_class': [False],
    'exp_field_class': [False],
    'country_argentina': [True],
    'country_australia': [False],
    'country_austria': [False],
    'country_bangladesh': [False],
    'country_belgium': [False],
    'country_bermuda': [False],
    'country_brazil': [False],
    'country_bulgaria': [False],
    'country_cambodia': [False],
    'country_canada': [False],
    'country_chile': [False],
    'country_china': [False],
    'country_costa rica': [False],
    'country_croatia': [False],
    'country_denmark': [False],
    'country_ecuador': [False],
    'country_england': [False],
    'country_eritrea': [False],
    'country_estonia': [False],
    'country_finland': [False],
    'country_france': [False],
    'country_germany': [False],
    'country_ghana': [False],
    'country_greece': [False],
    'country_hong kong': [False],
    'country_hungary': [False],
    'country_india': [False],
    'country_ireland': [False],
    'country_isle of man': [False],
    'country_israel': [False],
    'country_italy': [False],
    'country_jamaica': [False],
    'country_japan': [False],
    'country_jordan': [False],
    'country_kenya': [False],
    'country_kuwait': [False],
    'country_latvia': [False],
    'country_lithuania': [False],
    'country_luxembourg': [False],
    'country_malaysia': [False],
    'country_malta': [False],
    'country_mexico': [False],
    'country_morocco': [False],
    'country_netherlands': [False],
    'country_new zealand': [False],
    'country_norway': [False],
    'country_philippines': [False],
    'country_poland': [False],
    'country_portugal': [False],
    'country_puerto rico': [False],
    'country_qatar': [False],
    'country_romania': [False],
    'country_russia': [False],
    'country_rwanda': [False],
    'country_serbia': [False],
    'country_sierra leone': [False],
    'country_singapore': [False],
    'country_slovakia': [False],
    'country_slovenia': [False],
    'country_somalia': [False],
    'country_south africa': [False],
    'country_south korea': [False],
    'country_spain': [False],
    'country_sri lanka': [False],
    'country_sweden': [False],
    'country_switzerland': [False],
    'country_thailand': [False],
    'country_the bahamas': [False],
    'country_uganda': [False],
    'country_united arab emirates': [False],
    'country_united kingdom': [False],
    'country_united states': [False],
    'country_uruguay': [False],
    'country_vietnam': [False],
    'country_zimbabwe': [False],
    'industry_Agriculture or Forestry': [False],
    'industry_Art & Design': [False],
    'industry_Business or Consulting': [False],
    'industry_Computing or Tech': [False],
    'industry_Education (Higher Education)': [False],
    'industry_Education (Primary/Secondary)': [False],
    'industry_Engineering or Manufacturing': [False],
    'industry_Entertainment': [False],
    'industry_Government and Public Administration': [False],
    'industry_Health care': [False],
    'industry_Hospitality & Events': [False],
    'industry_Insurance': [False],
    'industry_Law': [False],
    'industry_Law Enforcement & Security': [False],
    'industry_Leisure, Sport & Tourism': [False],
    'industry_Marketing, Advertising & PR': [False],
    'industry_Media & Digital': [False],
    'industry_Nonprofits': [False],
    'industry_Other': [False],
    'industry_Property or Construction': [False],
    'industry_Recruitment or HR': [False],
    'industry_Retail': [False],
    'industry_Sales': [False],
    'industry_Social Work': [False],
    'industry_Transport or Logistics': [False],
    'industry_Utilities & Telecommunications': [False],
    'gender_Other': [False],
    'gender_Woman': [False]
})